# Class 1 Homework: Python thinking

This homework has more on the basics of Python. These are the kind of things that can cause errors, so we are going to practice making some errors and understanding what to do next.

Some of this material is also covered in the Python tutorial at https://docs.python.org/3/tutorial/introduction.html

It's also covered in Python for Biologists, by Martin Jones, and our recommended course books.

We'll load modules first, as it's helpful to have them at the beginning of a notebook, even though we won't use these until much later.

In [1]:
import numpy as np
import pandas as pd

## Python data types

What is the difference between these lines of code?

Before you run each line, try to predict the outcome.

If the line gives an error, try to understand it.

In [2]:
1 + 1

2

In [3]:
'1' + '1'

'11'

In [4]:
1 + '1'

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [5]:
one + one

NameError: name 'one' is not defined

In [6]:
'one' + 'one'

'oneone'

In [7]:
'one' + '1'

'one1'

Does 1 plus 1 equal 2, or 11?

This may seem absurd, but programming languages need to keep track of many different kinds of things: numbers, text, dates, data frames, etc.

Everything that Python plays with, has a "data type" that tracks what kind of thing it is, what the allowed values are, and what you can do with it. Most programming languages have a concept of "data type", to tell the difference between numbers, text, and so on. [Data type at simple english wikipedia](https://simple.wikipedia.org/wiki/Data_type).

**Quotes** around a Python object tell Python to interpret it as a string, i.e. text.

We'll use data frames mostly on this course. Data frames can contain different kinds of information in different columns - one column can be a number and another text. However, some background knowledge on how Python deals with other kinds of objects helps to understand how it works, and especially what goes wrong and how to fix it.

In Python, the `type` function tells you what kind of data a given thing is. Common data types include:

- int / integer for whole numbers
- float / numeric for non-whole numbers
- str / string for text
- datetime - basic dates and times
- bool / logical for True and False values. (bool is short for Boolean logic)

In [8]:
type(1)

int

In [9]:
type('1')

str

In [10]:
type(1.0)

float

In [11]:
type(True)

bool

So with code like `1 + '1'` - they are different types. It makes no sense to add a number to a string, so it's not allowed by Python.

But it does make sense to add two different kinds of numbers. So add an integer to a floating point number and you get another floating point number.

Note that Python tells you that it thinks a number is a floating point number by displaying the decimal place. What's happening in the next cells?

In [12]:
1 + 1.5

2.5

In [13]:
1 + 2

3

In [14]:
1 + 2.0

3.0

In [15]:
1.5 + 1.5

3.0

This can have intended, or unintended effects. For example, logical values can be interpreted `True` as `1`, and `False` as `0` - this is bad if you don't want it, and good if you do.

Try playing around with these to help you understand it.

In [16]:
1 + True

2

## Wait, can I just use Python as a calculator?

Yes you can. You can add, multiply, divide, and exponentiate to your heart's content.

More advanced functions, like logarithms and exponentials, tend to be found in the `numpy` module.

Play around here, if you like...

In [17]:
1000000 + 1

1000001

In [18]:
np.log2(8)

np.float64(3.0)

In [19]:
np.exp(10)

np.float64(22026.465794806718)

Again, there's more on this in the Python tutorial we linked to at the beginning.

Remember, the `+` sign can do different things on different data types. As you will be able to see from the exercises above, using the `+` operator to combine ints or floats will return ints and floats respectively. If there is a mix of ints and floats, then Python will return a float.

You may be thinking, but then why can I add two strings? Remember, operators and functions do different things on different data types. So when we use the `+` operator on strings, we are joining (or 'concatenating') them together.

In [20]:
'how' + ' ' + 'to' + ' ' + 'add' + ' ' + 'strings'

'how to add strings'

Using strings and the `+` operator, try writing some code in the cell below that will produce a short sentence, just like the example above.

## Functions

Functions have input and output - we are revising here from the material on functions in Discovery first year course.

One function we like to use is `print`, to display things.

In [21]:
print(1)

1

In [22]:
print(1 + 2)

3

In [23]:
type(print)

builtin_function_or_method

Functions take arguments, i.e. input, and they need to be written in Python with brackets in order to act. Otherwise they just, well, they just are there.

What's happening in the next few cells?

In [24]:
print

In [25]:
print()

In [26]:
print(print)

<built-in function print>

You can ask for help about functions using a `?` in Python

In [27]:
print?

Signature: print(*args, sep=' ', end='\n', file=None, flush=False)
Docstring:
Prints the values to a stream, or to sys.stdout by default.

sep
  string inserted between values, default a space.
end
  string appended after the last value, default a newline.
file
  a file-like object (stream); defaults to the current sys.stdout.
flush
  whether to forcibly flush the stream.
Type:      builtin_function_or_method

You can look inside existing functions, or write your own functions.

One of the workshops in Discovery wrote functions to calculate distances between two strings.

The code below defines a function to add one to whatever the input is.

In [28]:
def addone(x):
    return x + 1

In [29]:
addone(100)

101

You can play around with writing your own functions, if you want.

A big learning point here is that complex Python objects are build out of simpler Python objects.

## Lists

Often, we need to keep track of many different pieces of data together.

Python lists are the easiest way of doing this. They're created and displayed using square brackets.

In [30]:
[1, 2, 3]

[1, 2, 3]

In [31]:
type([1, 2, 3])

list

Adding two lists creates a longer list (or, "append" the second list).

In [32]:
[1, 2, 3] + [4]

[1, 2, 3, 4]

The importance of square brackets for defining lists means that having brackets in the wrong place can get confusing. Like quotes.

What's happening in the next examples?

In [33]:
[1] + [1]

[1, 1]

In [34]:
[1] + ['1']

[1, '1']

In [35]:
[1 + 1]

[2]

In [36]:
[1] + 1

TypeError: can only concatenate list (not "int") to list

Yes... when learning to code, it helps to be precise and even pedantic.

Lists can contain different kinds of objects.

In [37]:
[1, 2, "many"]

[1, 2, 'many']

That inconsistency can cause problems, so in this course we'll try to work with lists that contain only one kind of thing, like the columns of a data frame.

## Wait, what is a data frame really?

We now want to understand what kind of data type a data frame is. We'll re-use some of the material from Class 1 notebook.

Next make a dataframe

In [38]:
# example data frame with just numbers
df_simple = pd.DataFrame(
    {"a" : [4, 5, 6],
     "b" : [7, 8, 9] })

df_simple

   a  b
0  4  7
1  5  8
2  6  9

What kinds of objects are these?

In [39]:
type(pd.DataFrame)

type

In [40]:
type(df_simple)

pandas.DataFrame

This means that the "type" DataFrame is defined by the pandas module

Remember, you can ask for help on functions straight from your Python session.

In [41]:
pd.DataFrame?

Init signature:
pd.DataFrame(
    data=None,
    index: 'Axes | None' = None,
    columns: 'Axes | None' = None,
    dtype: 'Dtype | None' = None,
    copy: 'bool | None' = None,
) -> 'None'
Docstring:
Two-dimensional, size-mutable, potentially heterogeneous tabular data.

Data structure also contains labeled axes (rows and columns).
Arithmetic operations align on both row and column labels. Can be
thought of as a dict-like container for Series objects. The primary
pandas data structure.

Parameters
----------
data : ndarray (structured or homogeneous), Iterable, dict, or DataFrame
    Dict can contain Series, arrays, constants, dataclass or list-like objects. If
    data is a dict, column order follows insertion-order. If a dict contains Series
    which have an index defined, it is aligned by its index. This alignment also
    occurs if data is a Series or a DataFrame itself. Alignment is done on
    Series/DataFrame inputs.

    If data is a list of dicts, column order follows insertion-order.

index : Index or array-like
    Index to use for resulting frame. Will default to RangeIndex if
    no indexing information part of input data and no index provided.
columns : Index or array-like
    Column labels to use for resulting frame when data does not have them,
    defaulting to RangeIndex(0, 1, 2, ..., n). If data contains column labels,
    will perform column selection instead.
dtype : dtype, default None
    Data type to force. Only a single dtype is allowed. If None, infer.
    If ``data`` is DataFrame then is ignored.
copy : bool or None, default None
    Copy data from inputs.
    For dict data, the default of None behaves like ``copy=True``.  For DataFrame
    or 2d ndarray input, the default of None behaves like ``copy=False``.
    If data is a dict containing one or more Series (possibly of different dtypes),
    ``copy=False`` will ensure that these inputs are not copied.

See Also
--------
DataFrame.from_records : Constructor from tuples, also record arrays.
DataFrame.from_dict : From dicts of Series, arrays, or dicts.
read_csv : Read a comma-separated values (csv) file into DataFrame.
read_table : Read general delimited file into DataFrame.
read_clipboard : Read text from clipboard into DataFrame.

Notes
-----
Please reference the :ref:`User Guide <basics.dataframe>` for more information.

Examples
--------
Constructing DataFrame from a dictionary.

>>> d = {"col1": [1, 2], "col2": [3, 4]}
>>> df = pd.DataFrame(data=d)
>>> df
   col1  col2
0     1     3
1     2     4

Notice that the inferred dtype is int64.

>>> df.dtypes
col1    int64
col2    int64
dtype: object

To enforce a single dtype:

>>> df = pd.DataFrame(data=d, dtype=np.int8)
>>> df.dtypes
col1    int8
col2    int8
dtype: object

Constructing DataFrame from a dictionary including Series:

>>> d = {"col1": [0, 1, 2, 3], "col2": pd.Series([2, 3], index=[2, 3])}
>>> pd.DataFrame(data=d, index=[0, 1, 2, 3])
   col1  col2
0     0   NaN
1     1   NaN
2     2   2.0
3     3   3.0

Constructing DataFrame from numpy ndarray:

>>> df2 = pd.DataFrame(
...     np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]), columns=["a", "b", "c"]
... )
>>> df2
   a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

Constructing DataFrame from a numpy ndarray that has labeled columns:

>>> data = np.array(
...     [(1, 2, 3), (4, 5, 6), (7, 8, 9)],
...     dtype=[("a", "i4"), ("b", "i4"), ("c", "i4")],
... )
>>> df3 = pd.DataFrame(data, columns=["c", "a"])
>>> df3
   c  a
0  3  1
1  6  4
2  9  7

Constructing DataFrame from dataclass:

>>> from dataclasses import make_dataclass
>>> Point = make_dataclass("Point", [("x", int), ("y", int)])
>>> pd.DataFrame([Point(0, 0), Point(0, 3), Point(2, 3)])
   x  y
0  0  0
1  0  3
2  2  3

Constructing DataFrame from Series/DataFrame:

>>> ser = pd.Series([1, 2, 3], index=["a", "b", "c"])
>>> df = pd.DataFrame(data=ser, index=["a", "c"])
>>> df
   0
a  1
c  3

>>> df1 = pd.DataFrame([1, 2, 3], index=["a", "b", "c"], columns=["x"])
>>> df2 = pd.DataFrame(data=df1, index=["a", "c"])
>>> df2
   x
a  1
c  3
File:           /opt/conda/lib/python3.13/site-packages/pandas/__init__.py
Type:           type
Subclasses:     SubclassedDataFrame

These help files are usually findable on nicely formatted websites too. See https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html

In [42]:
# example data frame with numbers and names - taken from https://en.wikipedia.org/wiki/List_of_universities_in_Scotland
df_scottishuniversities = pd.DataFrame(
    {"University" : ["St Andrews", "Glasgow", "Aberdeen", "Edinburgh"],
     "Founding_year" : [1413, 1451, 1495, 1582],
     "Total_students_2023" : [11895, 38125, 15455, 40625 ]
    })

df_scottishuniversities

   University  Founding_year  Total_students_2023
0  St Andrews           1413                11895
1     Glasgow           1451                38125
2    Aberdeen           1495                15455
3   Edinburgh           1582                40625

In [43]:
type(df_scottishuniversities)

pandas.DataFrame

In [44]:
df_penguins = pd.read_csv('../Datasets/penguins.csv')

df_penguins

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male

Complex Python objects are made out of simpler Python objects. Clearly, this data frame contains both numbers and strings. It's arranged into columns and rows.

Conceptually, a dataframe is built out of columns.

Python calls a single column of a data frame a **Series**.  A Python Series is a bit like a Python list. However, a Series contains only one kind of data type, and has an order, index and, like dataframes, there are functions to describe and summarise them. A series can be called in different ways. Here are some examples of how we can quantify just the bill length measurements in the penguins dataset.

In the first example, we assign to a variable.

In [45]:
df_penguins_col = df_penguins['bill_length_mm']

In [46]:
max(df_penguins_col)

59.6

Some Python types, like the data frame, come with "built-in functions" (also called bound methods) that are accessed by using a dot at the end.

In [47]:
df_penguins_col.max()

np.float64(59.6)

In [48]:
df_penguins_col.max?

Signature:
df_penguins_col.max(
    *,
    axis: 'Axis | None' = 0,
    skipna: 'bool' = True,
    numeric_only: 'bool' = False,
    **kwargs,
)
Docstring:
Return the maximum of the values over the requested axis.

If you want the *index* of the maximum, use ``idxmax``.
This is the equivalent of the ``numpy.ndarray`` method ``argmax``.

Parameters
----------
axis : {index (0)}
    Axis for the function to be applied on.
    For `Series` this parameter is unused and defaults to 0.

    For DataFrames, specifying ``axis=None`` will apply the aggregation
    across both axes.

    .. versionadded:: 2.0.0

skipna : bool, default True
    Exclude NA/null values when computing the result.
numeric_only : bool, default False
    Include only float, int, boolean columns.
**kwargs
    Additional keyword arguments to be passed to the function.

Returns
-------
scalar or Series (if level specified)
    The maximum of the values in the Series.

See Also
--------
numpy.max : Equivalent numpy function for arrays.
Series.min : Return the minimum.
Series.max : Return the maximum.
Series.idxmin : Return the index of the minimum.
Series.idxmax : Return the index of the maximum.
DataFrame.min : Return the minimum over the requested axis.
DataFrame.max : Return the maximum over the requested axis.
DataFrame.idxmin : Return the index of the minimum over the requested axis.
DataFrame.idxmax : Return the index of the maximum over the requested axis.

Examples
--------
>>> idx = pd.MultiIndex.from_arrays(
...     [["warm", "warm", "cold", "cold"], ["dog", "falcon", "fish", "spider"]],
...     names=["blooded", "animal"],
... )
>>> s = pd.Series([4, 2, 0, 8], name="legs", index=idx)
>>> s
blooded  animal
warm     dog       4
         falcon    2
cold     fish      0
         spider    8
Name: legs, dtype: int64

>>> s.max()
8
File:      /opt/conda/lib/python3.13/site-packages/pandas/core/series.py
Type:      method

In these next examples, we avoid assigning the column to a variable and call it directly instead.

In [49]:
max(df_penguins['bill_length_mm'])

59.6

In [50]:
max(df_penguins.bill_length_mm) # note: this only works if the column name has no spaces or odd characters.

59.6

In [51]:
df_penguins['bill_length_mm'].max()

np.float64(59.6)

There are lots of functions you can use to summarise a series:  
    
-  `P.min()`
-  `P.mean()`
-  `P.median()`
-  `P.std()`
-  `P.skew()`
-  `P.quantile(0.5)`
-  `P.nlargest(3)`
-  `P.sample(2)`
-  `P.argmin()`
-  `P.argmax()`
-  `P.count()`
-  `P.value_counts()`

Have a go running some of these commands in the cells below. Can you work out what they are doing?

## Wait, what's going on?

The goal of this homework was to revise some Python basics, in a way that you can learn many key features and how to troubleshoot errors.

Thinking about about why these lines of code work the way they do will help you code in the rest of the course.

Yes, it requires precision and pedantry. It's like learning a language - it takes time and practice. By starting to understand what each component of a line of code does, you can learn to make the code work for you.

### The worst part - there's lots of ways of doing the same thing

Yes. This is the worst part. This is a frequent complaint about Python.

Learn one thing at a time, and you can learn to make Python work for you. Millions of people use Python and other coding languages every day - it gets easier as you learn to recognise patterns.